name: Build & Push Cal.com Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest   # Free runner
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable && corepack prepare yarn@1.22.22 --activate

      - name: Install deps
        working-directory: ./package
        run: yarn install --frozen-lockfile

      - name: Build web
        working-directory: ./package
        run: yarn build --filter web...

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: ./package
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/calcom:latest
